config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :surveys
  resources :memory_surveys
  resources :reading_surveys
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :memory_surveys, inverse_of: :survey, dependent: :destroy
  has_many :reading_surveys, inverse_of: :survey, dependent: :destroy
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show]

  def new
    @survey = Survey.find_by(:subject => subject)
    unless @survey
      @survey = Survey.create(:subject => subject)
    end

    @operational = true
    @possibles_memory = []
    @possibles_reading = []
    @reading = true

    if @survey.two_memory < 3
      @possibles_memory << 2
    end
    if @survey.three_memory < 3
      @possibles_memory << 3
    end
    if @survey.four_memory < 3
      @possibles_memory << 4
    end
    if @survey.five_memory < 3
      @possibles_memory << 5
    end
    if @survey.six_memory < 3
      @possibles_memory << 6
    end
    if @survey.seven_memory < 3
      @possibles_memory << 7
    end

    @questions = @possibles_memory.sample

    unless @questions
      @operational = false
    end

    unless @operational
      if @survey.two_reading < 3
        @possibles_reading << 2
      end
      if @survey.three_reading < 3
        @possibles_reading << 3
      end
      if @survey.four_reading < 3
        @possibles_reading << 4
      end
      if @survey.five_reading < 3
        @possibles_reading << 5
      end
      if @survey.six_reading < 3
        @possibles_reading << 6
      end
      if @survey.seven_reading < 3
        @possibles_reading << 7
      end

      @questions = @possibles_reading.sample

      unless @questions
        @reading = false
      end
    end
  end

  def show
  end

  private
    def set_survey
      @survey = Survey.find(params[:id])
    end

    def subject
      begin
        subject = params[:subject]
      rescue
        render :file => "public/401.html", :status => :unauthorized
      end

      subject
    end

    def survey_params
      params.require(:survey).permit(
        :subject,
      )
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/new.html.erb
<h1>Survey</h1>

<div class="instructions">
<% if @operational %>
  <%= link_to "Begin operational span", new_memory_survey_path(subject: @survey.subject, questions: @questions), data: { turbolinks: false } %>
<% elsif @reading %>
  <%= link_to "Begin reading span", new_reading_survey_path(subject: @survey.subject, questions: @questions), data: { turbolinks: false } %>
<% else %>
  <p>Thank you for participating. Your surveys are now complete.</p>
<% end %>
</div>

app/views/surveys/show.html.erb
<h1>Operational Span</h1>

<p id="notice"><%= notice %></p>

<p class="instructions">You will be redirected to the Reading Span in 5 seconds.</p>

<meta HTTP-EQUIV="REFRESH" content="5; url=<%= new_reading_survey_path %>?subject=<%= @survey.subject %>">